# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2025-2026 AegisGate Security. All rights reserved.

"""
AegisGate Python SDK v3.6.0

A comprehensive Python SDK for the AegisGate enterprise AI security platform.
Provides both synchronous and asynchronous clients with typed service methods
for all v3.6.0 API endpoints.

Basic Usage:
    from aegisgate import Client

    client = Client(base_url="http://localhost:8080", api_key="your-key")
    health = client.core.health()
    print(health)
    client.close()

Async Usage:
    from aegisgate import AsyncClient

    async with AsyncClient(base_url="http://localhost:8080") as client:
        health = await client.core.health()
        print(health)
"""

__version__ = "3.6.0"
__author__ = "AegisGate Security"

from aegisgate.client import Client, AsyncClient
from aegisgate.models import (
    Health,
    Version,
    Module,
    License as LicenseInfo,
    Violation,
    ScanReport,
    ComplianceReport,
    ComplianceIntegrity,
    EvidenceResult,
    TrustDashboard,
    TrustScore,
    TrustAnomaly,
    TrustCompliance,
    AnalyticsUsage,
    AnalyticsCost,
    AnalyticsAnomalies,
    AnalyticsDashboard,
    GuardrailsResult,
    BridgeResult,
    ClusterHealth,
    PersistenceResult,
    CertInfo,
    AuditEntry,
    Policy,
    SLAInfo,
    SIEMStatus,
    LicenseStatus,
    TSAStatus,
    TierInfo,
    AttestationResult,
    AIBOMResult,
    A2AIntentResult,
    DigestResult,
    Incident,
    IncidentTriage,
    IncidentResolve,
    EvaluatorResult,
    MLShadowMetrics,
    IOCManifest,
    IOCStatus,
    Webhook,
    User,
)
from aegisgate.services import (
    AuthService,
    AsyncAuthService,
    ProxyService,
    AsyncProxyService,
    ComplianceService,
    AsyncComplianceService,
    TrustService,
    AsyncTrustService,
    ScanService,
    AsyncScanService,
    GuardrailsService,
    AsyncGuardrailsService,
    AnalyticsService,
    AsyncAnalyticsService,
    IOCService,
    AsyncIOCService,
    SIEMService,
    AsyncSIEMService,
    MLService,
    AsyncMLService,
    AuditService,
    AsyncAuditService,
    PolicyService,
    AsyncPolicyService,
    ClusterService,
    AsyncClusterService,
    BridgeService,
    AsyncBridgeService,
    AttestationService,
    AsyncAttestationService,
    AIBOMService,
    AsyncAIBOMService,
    A2AService,
    AsyncA2AService,
    DigestService,
    AsyncDigestService,
    IncidentService,
    AsyncIncidentService,
    EvaluatorService,
    AsyncEvaluatorService,
    PersistenceService,
    AsyncPersistenceService,
    CertsService,
    AsyncCertsService,
    LicenseService,
    AsyncLicenseService,
    SLAService,
    AsyncSLAService,
    TSAService,
    AsyncTSAService,
    WebhookService,
    AsyncWebhookService,
    CoreService,
    AsyncCoreService,
)
from aegisgate.langchain import AegisGateCallback, AegisGateFilter

__all__ = [
    "Client",
    "AsyncClient",
    # Models
    "Health",
    "Version",
    "Module",
    "LicenseInfo",
    "Violation",
    "ScanReport",
    "ComplianceReport",
    "ComplianceIntegrity",
    "EvidenceResult",
    "TrustDashboard",
    "TrustScore",
    "TrustAnomaly",
    "TrustCompliance",
    "AnalyticsUsage",
    "AnalyticsCost",
    "AnalyticsAnomalies",
    "AnalyticsDashboard",
    "GuardrailsResult",
    "BridgeResult",
    "ClusterHealth",
    "PersistenceResult",
    "CertInfo",
    "AuditEntry",
    "Policy",
    "SLAInfo",
    "SIEMStatus",
    "LicenseStatus",
    "TSAStatus",
    "TierInfo",
    "AttestationResult",
    "AIBOMResult",
    "A2AIntentResult",
    "DigestResult",
    "Incident",
    "IncidentTriage",
    "IncidentResolve",
    "EvaluatorResult",
    "MLShadowMetrics",
    "IOCManifest",
    "IOCStatus",
    "Webhook",
    "User",
    # Services (sync)
    "AuthService",
    "ProxyService",
    "ComplianceService",
    "TrustService",
    "ScanService",
    "GuardrailsService",
    "AnalyticsService",
    "IOCService",
    "SIEMService",
    "MLService",
    "AuditService",
    "PolicyService",
    "ClusterService",
    "BridgeService",
    "AttestationService",
    "AIBOMService",
    "A2AService",
    "DigestService",
    "IncidentService",
    "EvaluatorService",
    "PersistenceService",
    "CertsService",
    "LicenseService",
    "SLAService",
    "TSAService",
    "WebhookService",
    "CoreService",
    # Services (async)
    "AsyncAuthService",
    "AsyncProxyService",
    "AsyncComplianceService",
    "AsyncTrustService",
    "AsyncScanService",
    "AsyncGuardrailsService",
    "AsyncAnalyticsService",
    "AsyncIOCService",
    "AsyncSIEMService",
    "AsyncMLService",
    "AsyncAuditService",
    "AsyncPolicyService",
    "AsyncClusterService",
    "AsyncBridgeService",
    "AsyncAttestationService",
    "AsyncAIBOMService",
    "AsyncA2AService",
    "AsyncDigestService",
    "AsyncIncidentService",
    "AsyncEvaluatorService",
    "AsyncPersistenceService",
    "AsyncCertsService",
    "AsyncLicenseService",
    "AsyncSLAService",
    "AsyncTSAService",
    "AsyncWebhookService",
    "AsyncCoreService",
    # LangChain
    "AegisGateCallback",
    "AegisGateFilter",
]
