// SPDX-License-Identifier: Apache-2.0
// =========================================================================
// AegisGate Lens - Build Tool: Bundler
// =========================================================================
//
// bundle.go copies the Lens source files from <src>/ into
// <dist>/, preserving the directory structure. There is no
// transformation: the bytes in <src> are the bytes in <dist>.
//
// The plain-JS source is already valid ES2020 JavaScript and
// does not need transpilation, bundling, or minification. The
// manifest's `content_scripts.js` array lists every file in
// load order; the browser loads them as separate scripts in
// the content-script isolated world. The service-worker uses
// `importScripts()` to load its own dependencies.
//
// This file is ~150 LOC, stdlib only, no external Go modules.
// See plans/AEGISGATE-LENS-D6-PLAIN-JS-RESUME.md §Phase 1.
//
// v0.1.0+ Lens Phase 1 (plain-JS pivot, 2026-06-19).
// =========================================================================

package main

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// bundle copies every Lens source file from cfg.Src to cfg.Dist,
// preserving subdirectory structure. The files are:
//   - manifest.json (the extension manifest)
//   - *.js (every plain JavaScript file in the source tree,
//     preserving subdirectories: util/, detectors/, privacy/,
//     storage, api/, etc.)
//   - *.html (the popup and welcome pages)
//   - icons/* (the extension icons, generated by icons.go)
//
// On success, the dist directory is a ready-to-load Chrome
// extension: every file referenced in manifest.json is present
// at the path the manifest expects.
//
// On failure, any partially-populated dist directory is left
// in place; the caller can decide whether to delete it. The
// build tool itself does not roll back.
func bundle(cfg *Config) error {
	if err := os.MkdirAll(cfg.Dist, 0o755); err != nil { // #nosec G301 G703 -- build output directory; mode is conventional for dist dirs
		return fmt.Errorf("mkdir dist: %w", err)
	}

	// 1. Copy manifest.json first (the source of truth for
	//    what files are needed).
	if err := copyFile(
		filepath.Join(cfg.Src, "manifest.json"),
		filepath.Join(cfg.Dist, "manifest.json"),
	); err != nil {
		return fmt.Errorf("copy manifest.json: %w", err)
	}

	// 2. Copy every .js file, preserving subdirectory structure.
	//    The manifest's content_scripts.js array references each
	//    file by its path relative to the extension root, so we
	//    must preserve that structure.
	jsCount, err := copyTree(cfg.Src, cfg.Dist, ".js")
	if err != nil {
		return fmt.Errorf("copy .js files: %w", err)
	}

	// 3. Copy every .html file (popup.html, welcome.html).
	htmlCount, err := copyTree(cfg.Src, cfg.Dist, ".html")
	if err != nil {
		return fmt.Errorf("copy .html files: %w", err)
	}

	// 3b. Copy every .wasm file (vendored ONNX Runtime WASM core).
	//     These are loaded by ort.min.js via fetch(chrome.runtime.getURL(...)).
	//     Without them, ort cannot initialize the inference session.
	//     Day 32: Path C - vendor ONNX Runtime Web (Lesson #98).
	wasmCount, err := copyTree(cfg.Src, cfg.Dist, ".wasm")
	if err != nil {
		return fmt.Errorf("copy .wasm files: %w", err)
	}

	// 3c. Copy every .mjs file (WASM loader glue for ort).
	//     The .mjs files are ESM modules that ort.min.js dynamically
	//     imports to bootstrap the WASM core.
	mjsCount, err := copyTree(cfg.Src, cfg.Dist, ".mjs")
	if err != nil {
		return fmt.Errorf("copy .mjs files: %w", err)
	}

	// 3d. Copy the vendor/ directory LICENSE and SHA256SUMS files
	//     (attribution and integrity verification artifacts).
	//     These are required for license compliance (MIT for ort)
	//     and threat-model documentation.
	vendorDocCount, err := copyVendorDocs(cfg.Src, cfg.Dist)
	if err != nil {
		return fmt.Errorf("copy vendor docs: %w", err)
	}

	// 4. Copy the icons/ directory if it exists. icons.go
	//    generates the icons into <src>/icons/ during build;
	//    if the user runs `build-lens-extension` before
	//    `icons.go`, the directory won't exist yet.
	iconCount, err := copyDirIfExists(
		filepath.Join(cfg.Src, "icons"),
		filepath.Join(cfg.Dist, "icons"),
	)
	if err != nil {
		return fmt.Errorf("copy icons: %w", err)
	}

	fmt.Fprintf(os.Stderr, "bundled: %d .js + %d .html + %d .wasm + %d .mjs + %d icons + %d vendor-docs\n",
		jsCount, htmlCount, wasmCount, mjsCount, iconCount, vendorDocCount)
	return nil
}

// copyFile copies a single file from src to dst, creating
// any parent directories needed at dst. File mode is 0o644.
func copyFile(src, dst string) error {
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil { // #nosec G301 G703 -- build output dir
		return fmt.Errorf("mkdir %s: %w", filepath.Dir(dst), err)
	}
	in, err := os.Open(src) // #nosec G304 G703 -- src is from the developer-supplied --src tree
	if err != nil {
		return fmt.Errorf("open %s: %w", src, err)
	}
	defer in.Close()
	out, err := os.OpenFile(dst, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0o600) // #nosec G304 G703 -- dst is in the build's --dist directory; G302 fixed (was 0o644)
	if err != nil {
		return fmt.Errorf("create %s: %w", dst, err)
	}
	defer out.Close()
	if _, err := io.Copy(out, in); err != nil {
		return fmt.Errorf("copy %s -> %s: %w", src, dst, err)
	}
	return nil
}

// copyTree walks srcRoot and copies every file with the given
// extension to dstRoot, preserving the relative path. Returns
// the number of files copied.
func copyTree(srcRoot, dstRoot, ext string) (int, error) {
	count := 0
	err := filepath.Walk(srcRoot, func(path string, info os.FileInfo, err error) error { // #nosec G703 G122 -- srcRoot is the developer-supplied --src tree
		if err != nil {
			return err
		}
		if info.IsDir() {
			// Skip the icons/ subdirectory here; it's copied
			// separately by copyDirIfExists so it can be optional.
			if path != srcRoot && filepath.Base(path) == "icons" {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(info.Name(), ext) {
			return nil
		}
		rel, err := filepath.Rel(srcRoot, path) // #nosec G304 G703 -- path is from filepath.Walk of --src tree
		if err != nil {
			return err
		}
		rel = filepath.ToSlash(rel)
		dst := filepath.Join(dstRoot, rel)
		if err := copyFile(path, dst); err != nil {
			return err
		}
		count++
		return nil
	})
	return count, err
}

// copyVendorDocs copies LICENSE and SHA256SUMS files from any
// vendored component directory (src/vendor/<name>/) to dist. These
// are required for license compliance (MIT for ONNX Runtime) and
// threat-model documentation (SHA-256 pins).
func copyVendorDocs(srcRoot, dstRoot string) (int, error) {
	vendorDir := filepath.Join(srcRoot, "vendor")
	info, err := os.Stat(vendorDir)
	if err != nil {
		if os.IsNotExist(err) {
			return 0, nil
		}
		return 0, err
	}
	if !info.IsDir() {
		return 0, nil
	}
	count := 0
	entries, err := os.ReadDir(vendorDir)
	if err != nil {
		return 0, err
	}
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		subDir := filepath.Join(vendorDir, entry.Name())
		subEntries, err := os.ReadDir(subDir)
		if err != nil {
			return 0, err
		}
		for _, f := range subEntries {
			if f.IsDir() {
				continue
			}
			name := f.Name()
			// Only copy LICENSE, SHA256SUMS, SOURCES.txt, README.md
			if name != "LICENSE" && name != "SHA256SUMS" && name != "SOURCES.txt" && name != "README.md" {
				continue
			}
			src := filepath.Join(subDir, name)
			dst := filepath.Join(dstRoot, "vendor", entry.Name(), name)
			if err := copyFile(src, dst); err != nil {
				return 0, err
			}
			count++
		}
	}
	return count, nil
}
// src exists. Returns the number of files copied, or 0 if src
// doesn't exist. Returns an error only for unexpected failures.
func copyDirIfExists(src, dst string) (int, error) {
	info, err := os.Stat(src) // #nosec G703 -- src is from the developer-supplied --src tree
	if err != nil {
		if os.IsNotExist(err) {
			return 0, nil
		}
		return 0, err
	}
	if !info.IsDir() {
		return 0, fmt.Errorf("not a directory: %s", src)
	}
	count := 0
	err = filepath.Walk(src, func(path string, info os.FileInfo, err error) error { // #nosec G703 G122 -- src is from --src tree
		if err != nil {
			return err
		}
		if info.IsDir() {
			return nil
		}
		rel, err := filepath.Rel(src, path) // #nosec G304 G703 -- path is from filepath.Walk of --src tree
		if err != nil {
			return err
		}
		dst := filepath.Join(dst, rel)
		if err := copyFile(path, dst); err != nil {
			return err
		}
		count++
		return nil
	})
	return count, err
}
