// SPDX-License-Identifier: Apache-2.0
// AegisGate Platform — k6 Payload Generator
//
// Reads tests/adversarial/corpus.yaml and generates tests/load/k6/payloads.js
// — a k6 ES module exporting the adversarial and benign payload arrays.
//
// This eliminates the dual-source-of-truth problem: corpus.yaml is the single
// source, and the k6 script imports the generated module.
//
// Usage:  go run scripts/generate-k6-payloads.go
// CI:     Run before `k6 run` to ensure payloads.js is in sync with corpus.yaml.
//         The CI step `Verify payload sync` regenerates and diffs — fails if
//         the committed payloads.js doesn't match the corpus.
//
// Output: tests/load/k6/payloads.js (overwritten)

package main

import (
	"bufio"
	"fmt"
	"os"
	"regexp"
	"strings"
)

type payload struct {
	id       string
	text     string
	pType    string // adversarial | benign
	pattern  string
	category string
}

func main() {
	// Hardcoded paths — not user-controlled (CodeQL G304).
	const corpusPath = "tests/adversarial/corpus.yaml"
	const outputPath = "tests/load/k6/payloads.js"

	if _, err := os.Stat(corpusPath); os.IsNotExist(err) {
		fmt.Fprintf(os.Stderr, "ERROR: corpus not found at %s\n", corpusPath)
		os.Exit(1)
	}

	payloads, err := parseCorpus(corpusPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "ERROR: %v\n", err)
		os.Exit(1)
	}

	var adversarial []payload
	var benign []payload
	for _, p := range payloads {
		switch p.pType {
		case "adversarial":
			adversarial = append(adversarial, p)
		case "benign":
			benign = append(benign, p)
		}
	}

	if err := generateJS(outputPath, adversarial, benign); err != nil {
		fmt.Fprintf(os.Stderr, "ERROR: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s: %d adversarial + %d benign = %d total payloads\n",
		outputPath, len(adversarial), len(benign), len(adversarial)+len(benign))
}

// parseCorpus reads the YAML corpus and extracts payload entries.
// We use a simple line-by-line parser rather than a full YAML library
// to avoid adding dependencies. The corpus format is simple and controlled.
func parseCorpus(path string) ([]payload, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("opening corpus: %w", err)
	}
	defer file.Close()

	var payloads []payload
	var current *payload

	idRe := regexp.MustCompile(`^\s+- id:\s*(.+)$`)
	// text can be double-quoted, single-quoted, or unquoted (bare)
	textDoubleRe := regexp.MustCompile(`^\s+text:\s*"(.*)"\s*$`)
	textSingleRe := regexp.MustCompile(`^\s+text:\s*'(.*)'\s*$`)
	textBareRe := regexp.MustCompile(`^\s+text:\s*(.+)$`)
	typeRe := regexp.MustCompile(`^\s+type:\s*(\w+)`)
	patternRe := regexp.MustCompile(`^\s+pattern:\s*"(.*)"`)

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := scanner.Text()

		// Skip comments and empty lines
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "#") || trimmed == "" {
			continue
		}

		if m := idRe.FindStringSubmatch(line); m != nil {
			// Save previous payload
			if current != nil {
				payloads = append(payloads, *current)
			}
			current = &payload{id: strings.TrimSpace(m[1])}
			continue
		}

		if current == nil {
			continue
		}

		if m := textDoubleRe.FindStringSubmatch(line); m != nil {
			current.text = m[1]
		} else if m := textSingleRe.FindStringSubmatch(line); m != nil {
			current.text = m[1]
		} else if m := textBareRe.FindStringSubmatch(line); m != nil {
			current.text = m[1]
		} else if m := typeRe.FindStringSubmatch(line); m != nil {
			current.pType = m[1]
		} else if m := patternRe.FindStringSubmatch(line); m != nil {
			current.pattern = m[1]
		}
	}

	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("scanning corpus: %w", err)
	}

	// Don't forget the last payload
	if current != nil {
		payloads = append(payloads, *current)
	}

	return payloads, nil
}

// generateJS writes the k6 ES module file.
func generateJS(path string, adversarial, benign []payload) error {
	var sb strings.Builder

	sb.WriteString("// AUTO-GENERATED by scripts/generate-k6-payloads.go — DO NOT EDIT MANUALLY.\n")
	sb.WriteString("// Source: tests/adversarial/corpus.yaml\n")
	sb.WriteString("// Regenerate: go run scripts/generate-k6-payloads.go\n")
	sb.WriteString("// CI verifies sync: if this file doesn't match corpus.yaml, CI fails.\n")
	sb.WriteString("\n")
	sb.WriteString("// Adversarial payloads (must be blocked)\n")
	sb.WriteString("export const adversarialPayloads = [\n")
	for _, p := range adversarial {
		// Escape single quotes in text
		escaped := strings.ReplaceAll(p.text, `\`, `\\`)
		escaped = strings.ReplaceAll(escaped, `'`, `\'`)
		pattern := p.pattern
		if pattern == "" {
			pattern = "unknown"
		}
		sb.WriteString(fmt.Sprintf("    { id: '%s', text: '%s', pattern: '%s' },\n",
			p.id, escaped, pattern))
	}
	sb.WriteString("];\n\n")

	sb.WriteString("// Benign payloads (must be allowed)\n")
	sb.WriteString("export const benignPayloads = [\n")
	for _, p := range benign {
		escaped := strings.ReplaceAll(p.text, `\`, `\\`)
		escaped = strings.ReplaceAll(escaped, `'`, `\'`)
		sb.WriteString(fmt.Sprintf("    '%s',\n", escaped))
	}
	sb.WriteString("];\n")

	return os.WriteFile(path, []byte(sb.String()), 0600)
}
