#!/bin/bash
# =========================================================================
# AegisGate Security Platform - Compliance Regression CI Gate
# =========================================================================
#
# Runs the compliance regression gate as a CI check. This script:
#
#   1. Loads (or creates) a baseline compliance snapshot from
#      compliance-baseline.json in the repo root.
#   2. Runs the compliance regression test suite which compares
#      current pattern/scan results against the baseline.
#   3. Exits 0 if no regressions are found, 1 if regressions
#      exceed thresholds.
#
# The regression gate ensures that compliance scan results don't
# silently regress between commits. If a pattern change causes
# score drops, new unenforced frameworks, or missing controls,
# this gate will catch it.
#
# Exit codes:
#   0 - No regressions detected (all checks pass)
#   1 - Regressions detected (CI should fail)
#   2 - Setup error (missing tools, bad config, etc.)
#
# Usage:
#   ./scripts/compliance-regression-gate.sh
#   ./scripts/compliance-regression-gate.sh --update-baseline
#
# Options:
#   --update-baseline   Regenerate the baseline from current state
#   --skip-if-no-baseline  Exit 0 if no baseline exists (first run)
#   --verbose            Print detailed comparison report
# =========================================================================

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BASELINE_FILE="${REPO_ROOT}/compliance-baseline.json"
VERBOSE=0
UPDATE_BASELINE=0
SKIP_IF_NO_BASELINE=0

# Parse arguments
for arg in "$@"; do
    case "$arg" in
        --update-baseline)
            UPDATE_BASELINE=1
            ;;
        --skip-if-no-baseline)
            SKIP_IF_NO_BASELINE=1
            ;;
        --verbose)
            VERBOSE=1
            ;;
        --help|-h)
            echo "Usage: $0 [--update-baseline] [--skip-if-no-base] [--verbose]"
            echo ""
            echo "  --update-baseline       Regenerate baseline from current state"
            echo "  --skip-if-no-baseline   Exit 0 if no baseline exists"
            echo "  --verbose               Print detailed report"
            exit 0
            ;;
        *)
            echo "Unknown argument: $arg"
            exit 2
            ;;
    esac
done

echo "## Compliance Regression CI Gate"
echo ""

# Step 1: Check for baseline file
if [ "$UPDATE_BASELINE" -eq 1 ]; then
    echo "🔄 Updating baseline from current compliance state..."
    go test ./pkg/compliance/ -run TestSnapshotBaseline -count=1 -v 2>&1 | tail -5
    # The baseline is generated by the test; in production you'd
    # run a dedicated tool. For CI, we rely on the regression tests.
    echo "✅ Baseline updated"
    exit 0
fi

if [ ! -f "$BASELINE_FILE" ]; then
    if [ "$SKIP_IF_NO_BASELINE" -eq 1 ]; then
        echo "⚠️  No baseline file found at $BASELINE_FILE"
        echo "   Skipping regression gate (first run or baseline not committed)"
        echo ""
        echo "   To create a baseline, run:"
        echo "     $0 --update-baseline"
        echo ""
        echo "   Then commit compliance-baseline.json to the repo."
        exit 0
    fi
    echo "❌ No baseline file found at $BASELINE_FILE"
    echo "   Run '$0 --update-baseline' to create one, then commit it."
    exit 2
fi

echo "📋 Baseline: $BASELINE_FILE"
echo ""

# Step 2: Run compliance regression tests
echo "🔍 Running compliance regression tests..."
echo ""

# Run the regression tests specifically
REGRESSION_RESULT=0
go test ./pkg/compliance/ -run "TestRegression|TestCompare|TestCheckInCI" \
    -count=1 -v 2>&1 | tee /tmp/regression-test-output.txt || REGRESSION_RESULT=$?

echo ""

# Step 3: Parse results
if [ "$REGRESSION_RESULT" -eq 0 ]; then
    echo "✅ Compliance regression gate PASSED"
    echo "   No regressions detected in compliance scan results."
    exit 0
else
    echo "❌ Compliance regression gate FAILED"
    echo "   Regressions detected. Review the output above."
    echo ""
    echo "   If the regression is intentional (e.g., a pattern was"
    echo "   deliberately weakened), update the baseline:"
    echo "     $0 --update-baseline"
    echo "     git add compliance-baseline.json"
    echo "     git commit -s -m 'chore: update compliance regression baseline'"
    exit 1
fi