// SPDX-License-Identifier: Apache-2.0
// AegisGate Platform — Detection Coverage Report Generator
//
// Reads scanner patterns and ATLAS techniques from the codebase
// and generates a Markdown report mapping coverage.
//
// Usage: go run scripts/generate-coverage-report.go
// Output: stdout (pipe to file for release notes)

package main

import (
	"fmt"
	"os"
	"regexp"
	"sort"
	"strings"
)

type patternInfo struct {
	Name        string
	Severity    string
	Category    string
	Description string
}

func extractPatterns(filePath string) ([]patternInfo, error) {
	content, err := os.ReadFile(filePath)
	if err != nil {
		return nil, err
	}

	text := string(content)

	// Extract pattern blocks: {Name: "...", Regex: ..., Severity: X, Category: Y, Description: "..."},
	nameRe := regexp.MustCompile(`Name:\s*"([^"]+)"`)
	sevRe := regexp.MustCompile(`Severity:\s*(\w+)`)
	catRe := regexp.MustCompile(`Category:\s*(\w+)`)
	descRe := regexp.MustCompile(`Description:\s*"([^"]+)"`)

	// Split by {Name: to get individual pattern blocks
	blocks := regexp.MustCompile(`\{Name:\s*"`).Split(text, -1)

	var patterns []patternInfo
	for i := 1; i < len(blocks); i++ {
		block := "{Name: \"" + blocks[i]

		nameMatch := nameRe.FindStringSubmatch(block)
		sevMatch := sevRe.FindStringSubmatch(block)
		catMatch := catRe.FindStringSubmatch(block)
		descMatch := descRe.FindStringSubmatch(block)

		p := patternInfo{}
		if len(nameMatch) > 1 {
			p.Name = nameMatch[1]
		}
		if len(sevMatch) > 1 {
			p.Severity = sevMatch[1]
		}
		if len(catMatch) > 1 {
			p.Category = catMatch[1]
		}
		if len(descMatch) > 1 {
			p.Description = descMatch[1]
		}
		if p.Name != "" {
			patterns = append(patterns, p)
		}
	}

	return patterns, nil
}

func main() {
	patternsFile := "pkg/scanner/patterns.go"
	if _, err := os.Stat(patternsFile); os.IsNotExist(err) {
		fmt.Fprintf(os.Stderr, "Error: %s not found (run from repo root)\n", patternsFile)
		os.Exit(1)
	}

	patterns, err := extractPatterns(patternsFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading patterns: %v\n", err)
		os.Exit(1)
	}

	// Sort by category then name
	sort.Slice(patterns, func(i, j int) bool {
		if patterns[i].Category != patterns[j].Category {
			return patterns[i].Category < patterns[j].Category
		}
		return patterns[i].Name < patterns[j].Name
	})

	// Count by category
	categoryCounts := make(map[string]int)
	sevCounts := make(map[string]int)
	for _, p := range patterns {
		categoryCounts[p.Category]++
		sevCounts[p.Severity]++
	}

	fmt.Println("# Detection Coverage Report")
	fmt.Println()
	fmt.Printf("**Total Patterns:** %d\n", len(patterns))
	fmt.Printf("**Categories:** %d\n", len(categoryCounts))
	fmt.Println()
	fmt.Println("## Summary by Category")
	fmt.Println()
	fmt.Println("| Category | Count |")
	fmt.Println("|---|---|")
	for _, cat := range sortedKeys(categoryCounts) {
		fmt.Printf("| %s | %d |\n", cat, categoryCounts[cat])
	}
	fmt.Println()
	fmt.Println("## Summary by Severity")
	fmt.Println()
	fmt.Println("| Severity | Count |")
	fmt.Println("|---|---|")
	for _, sev := range sortedKeys(sevCounts) {
		fmt.Printf("| %s | %d |\n", sev, sevCounts[sev])
	}
	fmt.Println()
	fmt.Println("## OWASP LLM Top 10 Coverage")
	fmt.Println()
	fmt.Println("| OWASP # | Title | Patterns | Status |")
	fmt.Println("|---|---|---|---|")

	owaspMap := map[string]string{
		"LLM01": "Prompt Injection",
		"LLM02": "Insecure Output Handling",
		"LLM04": "Model DoS",
		"LLM05": "Supply Chain",
		"LLM06": "Sensitive Information Disclosure",
		"LLM08": "Excessive Agency",
		"LLM09": "Overreliance",
		"LLM10": "Model Theft / Unbounded Consumption",
	}

	for _, key := range []string{"LLM01", "LLM02", "LLM04", "LLM05", "LLM06", "LLM08", "LLM09", "LLM10"} {
		var matches []string
		for _, p := range patterns {
			if strings.Contains(strings.ToLower(p.Name), strings.ToLower(key)) {
				matches = append(matches, p.Name)
			}
		}
		status := "✅ Covered"
		if len(matches) == 0 {
			status = "❌ Gap"
		}
		fmt.Printf("| %s | %s | %s | %s |\n", key, owaspMap[key], strings.Join(matches, ", "), status)
	}

	fmt.Println()
	fmt.Println("## All Patterns (Detailed)")
	fmt.Println()
	fmt.Println("| # | Name | Severity | Category | Description |")
	fmt.Println("|---|---|---|---|---|")
	for i, p := range patterns {
		fmt.Printf("| %d | `%s` | %s | %s | %s |\n", i+1, p.Name, p.Severity, p.Category, p.Description)
	}
	fmt.Println()
	fmt.Println("---")
	fmt.Println()
	fmt.Println("*Generated by `scripts/generate-coverage-report.go`*")
}

func sortedKeys(m map[string]int) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
