// SPDX-License-Identifier: Apache-2.0
// ============================================================================
// AegisGate Platform - Agent Protocol (ANP) Types
// ============================================================================

package anp

import (
	"encoding/json"
	"fmt"
	"time"
)

// TaskStatus represents the status of an agent task
type TaskStatus string

const (
	TaskStatusPending    TaskStatus = "pending"
	TaskStatusInProgress TaskStatus = "in_progress"
	TaskStatusCompleted  TaskStatus = "completed"
	TaskStatusFailed     TaskStatus = "failed"
	TaskStatusCanceled   TaskStatus = "canceled"
)

// Task represents an agent task in the Agent Protocol
type Task struct {
	ID          string            `json:"task_id"`
	SessionID   string            `json:"session_id"`
	AgentID     string            `json:"agent_id"`
	Status      TaskStatus        `json:"status"`
	CreatedAt   time.Time         `json:"created_at"`
	UpdatedAt   time.Time         `json:"updated_at"`
	CompletedAt *time.Time        `json:"completed_at,omitempty"`
	Metadata    map[string]string `json:"metadata,omitempty"`

	// Security fields
	Signature  []byte `json:"-"`
	ContractID string `json:"-"`
}

// NewTask creates a new ANP task
func NewTask(id, sessionID, agentID string) *Task {
	now := time.Now()
	return &Task{
		ID:        id,
		SessionID: sessionID,
		AgentID:   agentID,
		Status:    TaskStatusPending,
		CreatedAt: now,
		UpdatedAt: now,
		Metadata:  make(map[string]string),
	}
}

// StepStatus represents the status of a task step
type StepStatus string

const (
	StepStatusCreated     StepStatus = "created"
	StepStatusInProgress  StepStatus = "in_progress"
	StepStatusCompleted   StepStatus = "completed"
	StepStatusOutputSaved StepStatus = "output_saved"
)

// Step represents an individual action within a task
type Step struct {
	ID          string            `json:"step_id"`
	TaskID      string            `json:"task_id"`
	Index       int               `json:"index"`
	Status      StepStatus        `json:"status"`
	CreatedAt   time.Time         `json:"created_at"`
	CompletedAt *time.Time        `json:"completed_at,omitempty"`
	Input       json.RawMessage   `json:"input,omitempty"`
	Output      json.RawMessage   `json:"output,omitempty"`
	Metadata    map[string]string `json:"metadata,omitempty"`

	// Security fields
	PreviousHash string `json:"-"`
	Signature    []byte `json:"-"`
}

// NewStep creates a new step for a task
func NewStep(taskID string, index int, input json.RawMessage) *Step {
	return &Step{
		TaskID:    taskID,
		Index:     index,
		Status:    StepStatusCreated,
		CreatedAt: time.Now(),
		Input:     input,
		Metadata:  make(map[string]string),
	}
}

// Artifact represents a file or content generated by an agent
type Artifact struct {
	ID            string            `json:"artifact_id"`
	TaskID        string            `json:"task_id"`
	StepID        string            `json:"step_id"`
	Filename      string            `json:"filename"`
	ContentType   string            `json:"content_type"`
	Size          int64             `json:"size"`
	CreatedAt     time.Time         `json:"created_at"`
	Data          []byte            `json:"-"`
	Metadata      map[string]string `json:"metadata,omitempty"`
	IntegrityHash string            `json:"-"`
}

// NewArtifact creates a new artifact
func NewArtifact(taskID, stepID, filename, contentType string, data []byte) *Artifact {
	return &Artifact{
		TaskID:      taskID,
		StepID:      stepID,
		Filename:    filename,
		ContentType: contentType,
		Size:        int64(len(data)),
		CreatedAt:   time.Now(),
		Data:        data,
		Metadata:    make(map[string]string),
	}
}

// Message represents communication between agents
type Message struct {
	ID        string            `json:"message_id"`
	FromAgent string            `json:"from_agent"`
	ToAgent   string            `json:"to_agent"`
	Content   string            `json:"content"`
	Timestamp time.Time         `json:"timestamp"`
	Metadata  map[string]string `json:"metadata,omitempty"`
	Signature []byte            `json:"-"`
}

// NewMessage creates a new agent message
func NewMessage(fromAgent, toAgent, content string) *Message {
	return &Message{
		ID:        generateID(),
		FromAgent: fromAgent,
		ToAgent:   toAgent,
		Content:   content,
		Timestamp: time.Now(),
		Metadata:  make(map[string]string),
	}
}

// GuardDecision represents the decision of a guard check
type GuardDecision string

const (
	DecisionAllow           GuardDecision = "allow"
	DecisionBlock           GuardDecision = "block"
	DecisionRequireApproval GuardDecision = "require_approval"
	DecisionLogOnly         GuardDecision = "log_only"
)

// GuardResult represents the result of a guard check
type GuardResult struct {
	Decision    GuardDecision
	Reason      string
	MatchedRule string
	Severity    string
	Metadata    map[string]string
}

// NewGuardResult creates a new guard result
func NewGuardResult(decision GuardDecision, reason, rule, severity string) *GuardResult {
	return &GuardResult{
		Decision:    decision,
		Reason:      reason,
		MatchedRule: rule,
		Severity:    severity,
		Metadata:    make(map[string]string),
	}
}

// Allow returns true if the decision is allow
func (r *GuardResult) Allow() bool {
	return r.Decision == DecisionAllow
}

// SecurityContext contains security-relevant information for guard checks
type SecurityContext struct {
	AgentID      string
	SessionID    string
	ContractID   string
	TrustScore   float64
	Capabilities []string
	Protocol     string
	Timestamp    time.Time
	Metadata     map[string]string
}

// NewSecurityContext creates a security context
func NewSecurityContext(agentID, sessionID string) *SecurityContext {
	return &SecurityContext{
		AgentID:   agentID,
		SessionID: sessionID,
		Protocol:  "anp",
		Timestamp: time.Now(),
		Metadata:  make(map[string]string),
	}
}

// Config holds ANP guard configuration
type Config struct {
	MaxTasksPerMinute      int
	MaxStepsPerTask        int
	MaxArtifactsPerStep    int
	MaxMessageRate         int
	RequireSignature       bool
	RequireContract        bool
	MinTrustScore          float64
	ScanOutput             bool
	BlockPII               bool
	BlockSecrets           bool
	BlockToxicContent      bool
	MaxArtifactSizeMB      int
	AllowedContentTypes    []string
	BlockedExtensions      []string
	MaxMessageLength       int
	BlockSocialEngineering bool
}

// DefaultConfig returns the default ANP guard configuration
func DefaultConfig() *Config {
	return &Config{
		MaxTasksPerMinute:      100,
		MaxStepsPerTask:        1000,
		MaxArtifactsPerStep:    50,
		MaxMessageRate:         60,
		RequireSignature:       true,
		RequireContract:        true,
		MinTrustScore:          50.0,
		ScanOutput:             true,
		BlockPII:               true,
		BlockSecrets:           true,
		BlockToxicContent:      true,
		MaxArtifactSizeMB:      100,
		AllowedContentTypes:    []string{"text/plain", "text/html", "application/json", "application/octet-stream"},
		BlockedExtensions:      []string{".exe", ".dll", ".so", ".dylib", ".sh"},
		MaxMessageLength:       10000,
		BlockSocialEngineering: true,
	}
}

func generateID() string {
	return fmt.Sprintf("anp_%d_%s", time.Now().UnixNano(), randomString(8))
}

func randomString(length int) string {
	const charset = "abcdefghijklmnopqrstuvwxyz0123456789"
	b := make([]byte, length)
	for i := range b {
		b[i] = charset[int(time.Now().UnixNano())%len(charset)]
	}
	return string(b)
}
